### ISSUE TITLE
easy way to reset quiz answers

### ISSUE THREAD

**Issue by mneuschaefer** [LiaScript/docs#1]
Completing a quiz multiple times is very helpful for self-directed learning. Currently liascript "remembers" my quiz answers, on (mac) chromium even a hard reload does not delete them. The only way currently is to go to browser settings and to purge cache and associated files in the browser, which is a huge time sink and an tedious procedure to many users.

A button or any other way to easily reset quiz answers would be very helpful.

**Comment by andre-dietrich** [comment]
You made a good point. Currently all of your states are stored within IndexedDB per course. Thus, for every document/course a database is created. You can delete them manually via the developer console or, I added a special button (not that beautiful), under LiaScript settings, below the table of contents, there is a gearwheel, and the last element is a button, that can be used to reset the local database for a particular course.
PS: what is currently not mentioned within the docs. There is a version tag, within the main comment of every course in the format of 0.0.1. As long as the first number is a zero, you are in some kind of a development mode, thus, no data is stored locally within the indexedDB. If you change this to 1.xx.xx or something else, you can add additional quizzes, code, etc. to the end of your course and let it grow without a problem, but if you move already existing quizzes and code snippets, then you will have to make a major version change to 2.xx.xx or 3.xx.xx. This first number is also used as the version number for indexedDB...

**Comment by mneuschaefer** [comment]
I did not find the version tag, but the button is very helpful already (if you know where it is :-) )
+1 adding it to the manual. thanks!

**Comment by andre-dietrich** [comment]
Probably it was a bit misleading. You can insert a html comment to the beginning of your Markdown file. On github it is not visible, but for LiaScript it can provide some usefull metainformation, also the version ...

```html
<!--
author:   Full Name

email:    your@email.org

version:  0.0.1

language: en

narrator: US English Male

comment:  some basic comments on the content of this document ...

link:    https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css

script: https://whatever_JavaScript_library_you_think_might_be_usefull

import: https://the_url_of_an_foreign_course_and_thus_import_its_macros_and_js_and_css_and...
-->
```

If you are using the atom plugin [liascript_snippets](https://atom.io/packages/liascript-snippets) then you can simply start typing `liaheadermain` and a template definition is inserted to your document, or you can start a new project by typing liainit and it will generate a complete document-stub that can be used as the basis for your project ...
