### ISSUE TITLE
Animate.css isn't working in the docs

### ISSUE THREAD

**Issue by pwab** [LiaScript/docs#3]
Support for animate.css was removed, wasn't it?
Therefore the docs section about it should be removed because it isn't working anymore:

https://liascript.github.io/course/?https://raw.githubusercontent.com/liaScript/docs/master/README.md#49

**Comment by andre-dietrich** [comment]
Thanks, animate is still there but not natively as it was in the previous versions, thus it is possible to use
```md
<!--
...
link: https://...animate.css
-->

# title

Some text with infinite {0}{ *bounce* }<!-- class = "animated infinite bounce" style = "animation-delay: 5s;" --> ...
```

or, of course to use it in HTML directly ...
