### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by chgoe** [LiaScript/docs#7]
The "detailed installation instructions" appear to have moved, or at least the links are not working anymore:

Detailed installation instructions can be found [here](https://aizac.herokuapp.com/install-atom-with-liascript/).

Detailed installation instructions can be found [here](https://aizac.herokuapp.com/install-visual-studio-code-with-liascript/).

**Comment by andre-dietrich** [comment]
@chgoe in which documentation have you found these links, we will have to update these? We have gathered all of our information into one single blog now. The first link is now:

https://liascript.github.io/blog/install-atom-with-liascript/

and the second is

https://liascript.github.io/blog/install-visual-studio-code-with-liascript/

**Comment by chgoe** [comment]
Thank you very much for the links!

Apologies for the vague info, the broken links are located here:
https://github.com/LiaScript/docs/blob/392fd3ae91d68a9b4729ebc69a1ac83122e8e5ec/README.md?plain=1#L157
https://github.com/LiaScript/docs/blob/392fd3ae91d68a9b4729ebc69a1ac83122e8e5ec/README.md?plain=1#L169

**Comment by andre-dietrich** [comment]
Ups ... just fixed this ... I need to check also other links for this ...Thank you for pointing out ...
